on: [push]

jobs:
  hello_world_private_job:
    runs-on: ubuntu-latest
    name: Job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: toshihikoyanase/gh-actions-hello-world
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
